# Generated by Django 5.2 on 2025-12-04 16:48

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_autodetectedtransactionnamepage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodetectedtransactionnamepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='generictransactionnamepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
